import { categoryService } from "../services/categoryService";
import { productService } from "../services/productService";
import { supabase } from "../services/supabaseClient";
import { Category, Product } from "../types";

const SAMPLE_CATEGORIES = [
    { name: "Men", slug: "men", description: "Men's Fashion" },
    { name: "Women", slug: "women", description: "Women's Fashion" },
    { name: "Accessories", slug: "accessories", description: "Watches, Bags, and more" },
    { name: "Footwear", slug: "footwear", description: "Sneakers and Formal Shoes" },
];

const SAMPLE_PRODUCTS = [
    {
        name: "Classic White T-Shirt",
        price: 29.99,
        categoryName: "Men",
        description: "Premium cotton classic fit t-shirt.",
        image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
        stock: 100,
    },
    {
        name: "Slim Fit Denise Jeans",
        price: 59.99,
        categoryName: "Women",
        description: "High-waisted slim fit jeans.",
        image: "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
        stock: 50,
    },
    {
        name: "Leather Messenger Bag",
        price: 129.99,
        categoryName: "Accessories",
        description: "Genuine leather bag for work and travel.",
        image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
        stock: 25,
    },
    {
        name: "Running Sneakers",
        price: 89.99,
        categoryName: "Footwear",
        description: "Lightweight running shoes for daily use.",
        image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
        stock: 75,
    },
    {
        name: "Summer Floral Dress",
        price: 49.99,
        categoryName: "Women",
        description: "Light and breezy floral dress.",
        image: "https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
        stock: 40,
    },
    {
        name: "Minimalist Watch",
        price: 199.99,
        categoryName: "Accessories",
        description: "Elegant minimalist watch with leather strap.",
        image: "https://images.unsplash.com/photo-1524805444758-089113d48a6d?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
        stock: 15,
    },
    {
        name: "Oxford Button Down",
        price: 45.00,
        categoryName: "Men",
        description: "Crisp oxford shirt for office or casual wear.",
        image: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
        stock: 60,
    },
];

export const seedDatabase = async () => {
    console.log("Starting database seed...");

    // 1. Create Categories
    console.log("Creating categories...");
    const createdCategories: Category[] = [];
    try {
        const existing = await categoryService.getAllCategories();
        const existingNames = new Set(existing.map(c => c.name));

        for (const cat of SAMPLE_CATEGORIES) {
            if (!existingNames.has(cat.name)) {
                // created_at is auto-generated by database, so we omit it
                const newCat = await categoryService.createCategory(cat as Omit<Category, "id" | "productCount">);
                createdCategories.push(newCat);
                console.log(`Created category: ${cat.name}`);
            } else {
                const existingCat = existing.find(c => c.name === cat.name);
                if (existingCat) createdCategories.push(existingCat);
                console.log(`Category exists: ${cat.name}`);
            }
        }
    } catch (err) {
        console.error("Error creating categories:", err);
    }

    // Build category name to ID map
    const categoryMap = new Map(createdCategories.map(c => [c.name, c.id]));

    // 2. Create Products with category_id
    console.log("Creating products...");
    try {
        for (const prod of SAMPLE_PRODUCTS) {
            const categoryId = categoryMap.get(prod.categoryName);

            if (!categoryId) {
                console.warn(`Category not found for product: ${prod.name}`);
                continue;
            }

            const newProduct = await productService.createProduct({
                name: prod.name,
                price: prod.price,
                category_id: categoryId, // Use category_id instead of category string
                description: prod.description,
                image: prod.image,
                stock: prod.stock,
                isNew: true,
                rating: 4.5,
                reviews: 0,
            } as any);

            console.log(`Created product: ${prod.name}`);

            // 3. Create variants for each product
            const sizes = ['S', 'M', 'L', 'XL'];
            const colors = ['Black', 'White', 'Blue', 'Gray'];

            for (const size of sizes) {
                for (const color of colors) {
                    const { error } = await supabase.from('product_variants').insert({
                        product_id: newProduct.id,
                        size,
                        color,
                        stock_quantity: Math.floor(Math.random() * 30) + 10,
                        sku: `${newProduct.id}-${size}-${color}`.toUpperCase(),
                        price_adjustment: 0,
                    });

                    if (error) {
                        console.error(`Error creating variant for ${prod.name}:`, error);
                    }
                }
            }
            console.log(`Created variants for: ${prod.name}`);
        }
    } catch (err) {
        console.error("Error creating products:", err);
    }

    console.log("Seeding complete!");
    return true;
};
