-- =============================================
-- COUPON / DISCOUNT CODE FEATURE
-- Run this SQL in Supabase SQL Editor
-- =============================================

-- 1. Tạo bảng coupons
CREATE TABLE IF NOT EXISTS public.coupons (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code            TEXT NOT NULL UNIQUE,
    discount_type   TEXT NOT NULL CHECK (discount_type IN ('percentage', 'fixed')),
    discount_value  NUMERIC(10,2) NOT NULL CHECK (discount_value > 0),
    min_order_amount NUMERIC(10,2) DEFAULT 0,
    max_discount    NUMERIC(10,2),
    usage_limit     INT,
    used_count      INT DEFAULT 0,
    start_date      TIMESTAMPTZ DEFAULT now(),
    end_date        TIMESTAMPTZ,
    is_active       BOOLEAN DEFAULT true,
    created_at      TIMESTAMPTZ DEFAULT timezone('utc', now()) NOT NULL
);

ALTER TABLE public.coupons OWNER TO postgres;

COMMENT ON TABLE public.coupons IS 'Mã giảm giá cho đơn hàng';
COMMENT ON COLUMN public.coupons.code IS 'Mã coupon (VD: SALE20, SUMMER50K)';
COMMENT ON COLUMN public.coupons.discount_type IS 'percentage = giảm theo %, fixed = giảm số tiền cố định (VNĐ)';
COMMENT ON COLUMN public.coupons.discount_value IS 'Giá trị giảm (20 = 20% hoặc 50000 = 50,000₫)';
COMMENT ON COLUMN public.coupons.min_order_amount IS 'Giá trị đơn hàng tối thiểu để áp dụng';
COMMENT ON COLUMN public.coupons.max_discount IS 'Giới hạn giảm tối đa (chỉ dùng cho percentage)';
COMMENT ON COLUMN public.coupons.usage_limit IS 'Số lần sử dụng tối đa (NULL = không giới hạn)';
COMMENT ON COLUMN public.coupons.used_count IS 'Số lần đã sử dụng';

-- 2. Thêm cột coupon vào bảng orders
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS coupon_code TEXT;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS discount_amount NUMERIC(10,2) DEFAULT 0;

-- 3. RLS Policies cho bảng coupons
ALTER TABLE public.coupons ENABLE ROW LEVEL SECURITY;

-- Ai cũng có thể xem coupon đang active (để validate ở frontend)
CREATE POLICY "Public can view active coupons" ON public.coupons
    FOR SELECT USING (is_active = true);

-- Chỉ Admin mới được quản lý (CRUD) coupons
CREATE POLICY "Admin manage coupons" ON public.coupons
    FOR ALL USING (
        EXISTS (
            SELECT 1 FROM public.profiles
            WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
        )
    );

-- 4. Function validate + apply coupon (chạy ở server để an toàn)
CREATE OR REPLACE FUNCTION public.validate_coupon(p_code TEXT, p_order_total NUMERIC)
RETURNS JSON
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_coupon RECORD;
    v_discount NUMERIC;
BEGIN
    -- Tìm coupon
    SELECT * INTO v_coupon FROM public.coupons
    WHERE code = UPPER(TRIM(p_code)) AND is_active = true;

    IF NOT FOUND THEN
        RETURN json_build_object('valid', false, 'error', 'Mã giảm giá không tồn tại hoặc đã bị vô hiệu hóa');
    END IF;

    -- Kiểm tra ngày bắt đầu
    IF v_coupon.start_date IS NOT NULL AND now() < v_coupon.start_date THEN
        RETURN json_build_object('valid', false, 'error', 'Mã giảm giá chưa có hiệu lực');
    END IF;

    -- Kiểm tra hết hạn
    IF v_coupon.end_date IS NOT NULL AND now() > v_coupon.end_date THEN
        RETURN json_build_object('valid', false, 'error', 'Mã giảm giá đã hết hạn');
    END IF;

    -- Kiểm tra số lần sử dụng
    IF v_coupon.usage_limit IS NOT NULL AND v_coupon.used_count >= v_coupon.usage_limit THEN
        RETURN json_build_object('valid', false, 'error', 'Mã giảm giá đã hết lượt sử dụng');
    END IF;

    -- Kiểm tra đơn tối thiểu
    IF p_order_total < v_coupon.min_order_amount THEN
        RETURN json_build_object(
            'valid', false,
            'error', format('Đơn hàng tối thiểu %s₫ để sử dụng mã này', to_char(v_coupon.min_order_amount, 'FM999,999,999'))
        );
    END IF;

    -- Tính số tiền giảm
    IF v_coupon.discount_type = 'percentage' THEN
        v_discount := p_order_total * v_coupon.discount_value / 100;
        -- Áp dụng giới hạn giảm tối đa
        IF v_coupon.max_discount IS NOT NULL AND v_discount > v_coupon.max_discount THEN
            v_discount := v_coupon.max_discount;
        END IF;
    ELSE
        v_discount := v_coupon.discount_value;
    END IF;

    -- Không giảm nhiều hơn tổng đơn
    IF v_discount > p_order_total THEN
        v_discount := p_order_total;
    END IF;

    RETURN json_build_object(
        'valid', true,
        'discount', v_discount,
        'discount_type', v_coupon.discount_type,
        'discount_value', v_coupon.discount_value,
        'code', v_coupon.code
    );
END;
$$;

-- 5. Function tăng used_count khi đặt hàng thành công
CREATE OR REPLACE FUNCTION public.use_coupon(p_code TEXT)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    UPDATE public.coupons
    SET used_count = used_count + 1
    WHERE code = UPPER(TRIM(p_code)) AND is_active = true;
END;
$$;

-- 6. Thêm một số coupon mẫu để test
INSERT INTO public.coupons (code, discount_type, discount_value, min_order_amount, max_discount, usage_limit, is_active)
VALUES
    ('WELCOME10', 'percentage', 10, 100000, 50000, 100, true),
    ('GIAM50K', 'fixed', 50000, 200000, NULL, 50, true),
    ('SALE20', 'percentage', 20, 300000, 100000, NULL, true)
ON CONFLICT (code) DO NOTHING;
